const express = require('express')
const cors = require('cors')
const cookieparser = require('cookie-parser')
const AdminRouter = require('./Administrator/AdminRouter')
require('dotenv').config()
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
const productRouter = require('./Products/productRouter')
const app = express()
const uri = process.env.URI
const port = process.env.PORT || 8080
app.use(bodyParser.json())
app.use(cors({origin:'*', credentials:true}))
app.use(cookieparser())
app.use(bodyParser.urlencoded({extended:false}))
app.get('/', (req, res) => res.status(200).send('The API is working normally!'))
app.use('/products', productRouter)
app.use('/admin', AdminRouter)
mongoose.connect(uri, {dbName:"BAdmin"}).then(() => console.log('Connected to mongodb')).catch(err => console.error(err))
app.listen(port, () => console.log(`The server is running at http://localhost:${port}`))